config/routes.rb
Qaprojects::Application.routes.draw do

	resources :users
	resources :sessions, only: [:new, :create, :destroy]
  
	root to: 'static_pages#home'

  match 'help', to: 'static_pages#help'
	
	match 'signin', to: 'sessions#new', via: :get
	match 'signin', to: 'sessions#create', via: :post
	match 'signout', to: 'sessions#destroy', via: :delete

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  username   :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class User < ActiveRecord::Base
  attr_accessible :username

	validates :username,
		presence: true,
		uniqueness: true

	before_save :create_remember_token

	private
		
		def create_remember_token
			self.remember_token = SecureRandom.urlsafe_base64
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
	include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	require 'jira'

	def new

	end

	def create
		username = params[:session][:username]
		password = params[:session][:password]
		if Jira::User.authenticate(username, password)
			if User.find_by_username(username)
				@user = User.find_by_username(username)
			else
				@user = User.create({username: username})
			end
			if sign_in @user
				flash[:notify] = "Signed In"
				redirect_to @user
			else
				flash.now[:error] = "Error signing in"
				render 'new'
			end
		else
			flash.now[:error] = "Invalid username/password"
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_path
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	require 'jira'

  def show
		@user = User.find(params[:id])
	end
	
	def new
  end

	def create
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis
	def full_title(page_title)
		base_title = "QA Projects"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end

end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		cookies.permanent[:remember_token] = user.remember_token
		current_user = user
	end

	def sign_out
		current_user = nil
		cookies.delete(:remember_token)
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		@current_user ||= User.find_by_remember_token(cookies[:remember_token])
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class='footer'>
	<div class='container'>
		<small>
			Made for
			<a href='http://gamesalad.com'>GameSalad</a>
		</small>
		<nav>
			<ul>
				<li><%= link_to "Contact",		"#" %></li>
			</ul>
		</nav>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header class='navbar navbar-fixed-top'>
	<div class='navbar-inner'>
		<div class='container'>
			<%= link_to "QA Projects", root_path, id: 'logo' %>
			<nav>
				<ul class='nav pull-right'>
					<li><%= link_to "Home",			root_path %></li>
					<li><%= link_to "Help",			help_path %></li>
					<% if signed_in? %>
						<li><%= link_to "Users", "#" %></li>
						<li id='fat-menu' class='dropdown'>
							<a href="#" class='dropdown-toggle' data-toggle='dropdown'>
								Account <b class='caret'></b>
							</a>
							<ul class='dropdown-menu'>
								<li><%= link_to "Profile", current_user %></li>
								<li><%= link_to "Settings", "#" %></li>
								<li class='divider'></li>
								<li>
									<%= link_to "Sign Out", signout_path, method: :delete %>
								</li>
							</ul>
						</li>
					<% else %>
						<li><%= link_to "Sign In",	signin_path %></li>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= full_title(yield(:title)) %></title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class='container'>
			<% flash.each do |key, value| %>
				<div class='alert alert-<%= key %>'><%= value %></div>
			<% end %>
			<%= yield %>
		</div>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</body>
</html>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>Help Page of the QA Projects Hosting Site.</p>

app/views/static_pages/home.html.erb
<div class='center hero-unit'>
	<h1>QA Projects Home</h1>

	<h2>
		This site is for GameSalad employees only.
		Please sign in below.
	</h2>

	<%= link_to "Sign In", signin_path, class: "btn btn-large btn-primary" %>
</div>

app/views/users/new.html.erb
<% provide(:title, "Sign In") %>
<h1>Sign In</h1>
<div class='row'>
	<div class='span6 offset3'>
		<%= form_tag(users_path, method: "post") do %>
			<%= label_tag :username %>
			<%= text_field_tag :username %>

			<%= label_tag :password %>
			<%= password_field_tag :password %>

			<%= submit_tag "Sign In", class: 'btn btn-large brn-primary' %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>
<div class='row'>
	<aside class='span4'>
		<section>
			<h1>
				<%= @user.username %>
			</h1>
		</section>
	</aside>
</div>